config/routes.rb
Talk::Application.routes.draw do
  resources :users
  resources :likes

  get "topics/backlog"
  resources :topics do
  resources :posts, :only => [:create]
  end

  resources :sessions

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

   root :to => 'topics#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :link, :source, :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :name, :topic_id
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :body, :name, :title, :tag, :attachment


  belongs_to :user
  has_many :posts, :dependent => :destroy
  has_attached_file :attachment

  def self.search(search_query)
    if search_query
      find(:all, :conditions => ['title LIKE ?', "%#{ search_query}%"])
    else
      find(:all)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin, :name, :password

  has_many :topics

  def self.authenticate(name, password)
    user = find_by_name(name)
    return user if user && user.authenticated?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by_id(session[:user_id])
  end

  helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @likes }
    end
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
    @like = Like.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @like }
    end
  end

  # GET /likes/new
  # GET /likes/new.json
  def new
    @like = Like.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @like }
    end
  end

  # GET /likes/1/edit
  def edit
    @like = Like.find(params[:id])
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(params[:like])

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render json: @like, status: :created, location: @like }
      else
        format.html { render action: "new" }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /likes/1
  # PUT /likes/1.json
  def update
    @like = Like.find(params[:id])

    respond_to do |format|
      if @like.update_attributes(params[:like])
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like = Like.find(params[:id])
    @like.destroy

    respond_to do |format|
      format.html { redirect_to likes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @topic = Topic.find(params[:topic_id])
    @topic.posts.create(params[:post])
    redirect_to @topic
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
  @user = User.new(params[:user])
  user = User.find_by_name_and_password(params[:name], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_path, :notice => "Now Logged in"
  else
    redirect_to root_path, :notice => "Incorrect Password"
  end
end

  def destroy
    reset_session
    redirect_to root_path, :notice => "Logged Out"
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index

    @topics = Topic.order("created_at DESC").paginate(:page => params[:main_articles_page], :per_page => 2)
    @general = Topic.order("created_at DESC").find(:all, :conditions => { :tag => "General" })
    @football = Topic.order("created_at DESC").find(:all, :conditions => { :tag => "Football" })
    @topics_all = Topic.search(params[:search_query]).take(5)


    @likes = Like.order('created_at DESC').take(5)
    @user = User.new

  end

  # GET /topics/1
  # GET /topics/1.json
  def show

    @topic = Topic.find(params[:id])
    @post = Post.new(params[:post])
    @posts = @topic.posts


  end

  def backlog
    #@topics = Topic.order( where  :tag => "General").paginate(:page => params[:main_articles_page], :per_page => 2)
    #@topics_all = Topic.find(:all, :order => "tag" )
    @football = Topic.order("created_at DESC").find(:all, :conditions => { :tag => "Football" }).take(2)
    @general = Topic.order("created_at DESC").find(:all, :conditions => { :tag => "General" }).take(2)
    @food = Topic.order("created_at DESC").find(:all, :conditions => { :tag => "Food" }).take(2)
    @travel = Topic.order("created_at DESC").find(:all, :conditions => { :tag => "Travel" }).take(2)
    @today = Topic.order("created_at DESC").find(:all, :conditions => [" created_at between ? AND ?", Time.zone.now.beginning_of_day, Time.zone.now.end_of_day])
    @months = Topic.order("created_at DESC").find(:all, :conditions => [" created_at between ? AND ?", Time.zone.now.beginning_of_month, Time.zone.now.end_of_month])
  end
  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(params[:user])

    if request.post?
      @user = User.new(params[:user])
      if @user.save
        redirect_to root_path, :notice => "Hello #{@user.name}! Please Log In."
      else
        redirect_to root_path, :notice => 'Try another Username.'
      end

    end

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mo Mews Mo Problems</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="outwrap">

<div id="bar">
  <%= link_to image_tag('logo.png'), root_path %>
  <%= link_to image_tag('twitter.png'), "http://ie.linkedin.com/in/danielreynolds7a/" %>
  <%= link_to image_tag('facebook.png'), "http://ie.linkedin.com/in/danielreynolds7a/" %>
  <a href="mailto:daniel.reynolds7a@gmail.com?Subject=GeneralMail" target="_top"><%= image_tag('mail.png') %></a>
  <div id="login" >

    <%= render 'sessions/login' %>
  </div>

  <div id="register" >

    <%= render 'users/form' %>
  </div>

 <!-- -->
<div id="nav">

  <% unless current_user %>
      <%= link_to 'Home', root_path %>
      <a onclick="show_login()" class="pointer">Login</a>
      <a onclick="show_register()" class="pointer">Register</a>
    <%end %>
  <% if current_user && current_user.admin %>
   <%= link_to 'New Article', new_topic_path %>
   <%= link_to 'New Like', new_like_path %>

      <% end %>
  <% if current_user %>
      <%= link_to "Logout", logout_path %>
  <% end %>

</div>




</div>


<div id="wrapper">
  <div id="quotes">
    <%= image_tag "quote1.png" %>
    <!--<%= image_tag "quote2.png" %> -->
    <%= image_tag "quote3.png" %>
   <!-- <%= image_tag "quote4.png" %>
    <%= image_tag "quote5.png" %>  -->
  </div>
  <hr />





<%= yield %>

</div>

</div>
<hr />
<script src="jquery-1.9.1.min.js"></script>
<script src="jquery.cycle.all.js"></script>
<script src="script.js"></script>
<!-- <div id="register_box"><a onclick="scroll_top()" class="pointer"><%= image_tag('totop.png') %></a></div> _-->
<!--<div id="notice"><%= notice %>THIS IS A NOTICE</div>-->
</body>
</html>

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>


  <div>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div>
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/likes/_likes.html.erb
<% @likes.each do|like| %>



    <p><a href="<%= like.link %>"><%= like.title %></a></p>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<div id="likes_page">
<h1>Likes: These Are The Articles I want to Share</h1>
<hr />
<%= render 'likes/likes' %>
</div>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render 'form' %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @like.title %>
</p>

<p>
  <b>Source:</b>
  <%= @like.source %>
</p>

<p>
  <b>Link:</b>
  <%= @like.link %>
</p>


<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/posts/_form.html.erb
<%= form_for [@topic, @post], :remote => true do |f| %>
    <%= f.text_area :body, :rows => 10, :cols => 40 %>
    <%= f.hidden_field :name, :value => "#{current_user.name}" %>
    <%= f.hidden_field :topic_id, :value => "#{@topic.id}" %><br />
    <%= submit_tag "Create" %>
<% end %>

app/views/posts/_post.html.erb
  <% @posts.each do|post| %>

 <span id="byline"><%= post.name %></span>
 <p><%= post.body %></p>
  <% end %>

app/views/topics/_food.html.erb
<% @food.each do |topic| %>
    <span id="byline"><%= topic.name %> - <%= topic.created_at.strftime("%A, %b %d") %></span>
    <h1><%= link_to topic.title, topic %></h1>
    <hr />
    <% if topic.attachment.file? %>
        <%= image_tag topic.attachment.url, :class => "picture" %>
    <% end %>
    <%= simple_format(truncate(topic.body, :length => 1000)) %>
    <%= link_to "Read More", topic, :class => "read_more" %>


      <% if current_user && current_user.admin %>
          - <%= link_to 'Edit', edit_topic_path(topic), :class => "read_more" %> -
          <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => "read_more" %>
      <% end %>
      <hr />
<% end %>

app/views/topics/_football.html.erb
<% @football.each do |topic| %>
    <span id="byline"><%= topic.name %> - <%= topic.created_at.strftime("%A, %b %d") %></span>
    <h1><%= link_to topic.title, topic %></h1>
    <hr />
    <% if topic.attachment.file? %>
        <%= image_tag topic.attachment.url, :class => "picture" %>
    <% end %>
    <%= simple_format(truncate(topic.body, :length => 1000)) %>
    <%= link_to "Read More", topic, :class => "read_more" %>


    <% if current_user && current_user.admin %>
        - <%= link_to 'Edit', edit_topic_path(topic), :class => "read_more" %> -
        <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => "read_more" %>
    <% end %>
    <hr />
<% end %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>

    <p>
      <%= f.label :title %><br />
      <%= f.text_area :title, :size => "100x1" %>
    </p>
    <p>
    <%= f.label :body %><br />
    <%= f.text_area :body, :size => "100x30" %>
  </p>
    <p>
      <%= f.label :attachment, 'Picture??' %><br />
      <%= f.file_field :attachment %><br />
    </p>
    <p>
      <%= f.label :tag, 'Tag It!' %><br />
      <%= f.select :tag, ['General', 'Football', 'Ramblings', 'Travel', 'Food'] %><br />
    </p>

    <p>
  <p>
    <%= f.hidden_field :name, :value => "#{current_user.name}"  %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/topics/_general.html.erb
<% @general.each do |topic| %>
    <span id="byline"><%= topic.name %> - <%= topic.created_at.strftime("%A, %b %d") %></span>
    <h1><%= link_to topic.title, topic %></h1>
    <hr />
    <% if topic.attachment.file? %>
        <%= image_tag topic.attachment.url, :class => "picture" %>
    <% end %>
    <%= simple_format(truncate(topic.body, :length => 1000)) %>
    <%= link_to "Read More", topic, :class => "read_more" %>
    <hr />
    <ul>
      <% if current_user && current_user.admin %>
          <li><%= link_to 'Edit', edit_topic_path(topic) %></li>
          <li><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
    </ul>
<% end %>

app/views/topics/_list.html.erb
<% @topics_all.each do|topic| %>

        <p><%= link_to topic.title, topic %></p>
<% end %>

<span class="title"> <%= link_to 'View Archives', topics_backlog_path %></span>

app/views/topics/_months.html.erb
<% @months.each do |topic| %>
    <span id="byline"><%= topic.name %> - <%= topic.created_at.strftime("%A, %b %d") %></span>
    <h1><%= link_to topic.title, topic %></h1>
    <hr />
    <% if topic.attachment.file? %>
        <%= image_tag topic.attachment.url, :class => "picture" %>
    <% end %>
    <%= simple_format(truncate(topic.body, :length => 1000)) %>
    <%= link_to "Read More", topic, :class => "read_more" %>


    <% if current_user && current_user.admin %>
        - <%= link_to 'Edit', edit_topic_path(topic), :class => "read_more" %> -
        <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => "read_more" %>
    <% end %>
    <hr />
<% end %>

app/views/topics/_today.html.erb
<% if @today.any? %>
<% @today.each do |topic| %>
    <span id="byline"><%= topic.name %> - <%= topic.created_at.strftime("%A, %b %d") %></span>
    <h1><%= link_to topic.title, topic %></h1>
    <hr />
    <% if topic.attachment.file? %>
        <%= image_tag topic.attachment.url, :class => "picture" %>
    <% end %>
    <%= simple_format(truncate(topic.body, :length => 1000)) %>
    <%= link_to "Read More", topic, :class => "read_more" %>


    <% if current_user && current_user.admin %>
        - <%= link_to 'Edit', edit_topic_path(topic), :class => "read_more" %> -
        <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => "read_more" %>
    <% end %>
    <hr />
<% end %>
<% else %>
<span class="title">Sorry. There are no articles published today.</span>
<% end %>

app/views/topics/_travel.html.erb
<% @travel.each do |topic| %>
    <span id="byline"><%= topic.name %> - <%= topic.created_at.strftime("%A, %b %d") %></span>
    <h1><%= link_to topic.title, topic %></h1>
    <hr />
    <% if topic.attachment.file? %>
        <%= image_tag topic.attachment.url, :class => "picture" %>
    <% end %>
    <%= simple_format(truncate(topic.body, :length => 1000)) %>
    <%= link_to "Read More", topic, :class => "read_more" %>


    <% if current_user && current_user.admin %>
        - <%= link_to 'Edit', edit_topic_path(topic), :class => "read_more" %> -
        <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => "read_more" %>
    <% end %>
    <hr />
<% end %>

app/views/topics/backlog.html.erb
<div id="tagbar">
  <span class="KG">I </span>
  <%= image_tag 'heart.png' %>
  <a onclick="show_football1()" class="pointer">Football </a> -
  <a onclick="show_travel1()" class="pointer">Travel </a> -
  <a onclick="show_food1()" class="pointer">Food </a> -
  <a onclick="show_general1()" class="pointer">General </a> -
  <a onclick="show_today()" class="pointer">Today's </a> -
  <a onclick="show_month()" class="pointer">This Month's </a> -
  <a onclick="show_all1()" class="pointer"> View All</a></div>
  <div id="archives">
  <div id="football"><%= render 'topics/football' %></div>
  <div id="general"><%= render 'topics/general' %></div>
  <div id="travel"><%= render 'topics/travel' %></div>
  <div id="food"><%= render 'topics/food' %></div>
    <div id="today"><%= render 'topics/today' %></div>
    <div id="month"><%= render 'topics/months' %></div>
  </div>

app/views/topics/content.html.erb
<div id="football">
<%= render 'topics/football' %>
</div>

app/views/topics/index.html.erb
<div id="tables_box">
  <table>
    <tr><td><h1>Links</h1></td></tr>
    <tr><td><a href="mailto:daniel.reynolds7a@gmail.com?Subject=Article" target="_top"> Send Me an Article</a></td></tr>
    <tr><td><a href="#nav" onclick="show_register()" class="pointer">Register To Comment</a></td></tr>
    <tr><td><a href="mailto:daniel.reynolds7a@gmail.com?Subject=Author" target="_top">Become An Author'</a></td></tr>
    <tr><td><%= link_to 'View Archives', topics_backlog_path %></td></tr>
    <tr><td><a href="mailto:daniel.reynolds7a@gmail.com?Subject=GeneralMail" target="_top">Mail Me</a></td></tr>
    <tr><td><a href="mailto:daniel.reynolds7a@gmail.com?Subject=WebDesign" target="_top">Request Web Design?</a></td></tr>
    <tr><td><%= link_to 'About Me', "http://dan.fernconsult.ie", :target => "_blank" %></td></tr>

  </table>

    <table id="table2">

    <form name="contact" onsubmit="return validateForm();" action="mailto:daniel.reynolds7a@gmail.com?subject=Customer_Inquiry" enctype="text/plain"  method="post" >
      <tr><td><label>Your name:</label></td></tr>
      <tr><td><input type="text" name="First Name" id="fname" /></td></tr>
      <tr><td><label>E-mail: </label></td></tr>
      <tr><td><input type="text" name="E-mail" id="email"/></td></tr>
      <tr><td><label>Message: </label> <textarea name="Message" id="Message" rows="9" cols="16"></textarea></td></tr>
      <tr><td><%= image_submit_tag("submit.png")%></td></tr>

    </form>

    </table>




</div>
<div id="special_box">
<div class="specials">
  <p id="cat">
    <a onclick="show_football()" class="pointer"><%= image_tag 'football.png' %> </a>|
    <a onclick="show_travel()" class="pointer"><%= image_tag 'travel.png' %> </a>|
    <a onclick="show_food()" class="pointer"><%= image_tag 'food.png' %></a>|
    <a onclick="show_general()" class="pointer"><%= image_tag 'general.png' %> </a>
  </p>
</div>
  <div class="specials">
    <h2 id="green">Tune of the Week</h2>
    <p>

      <%= image_tag 'tune.png', :class => "fl" %>
      <span class="title">Artist:</span>Explosions in The Sky<br />& David Wingo<br />
      <span class="title">Song:</span>Send Off<br /><br />

      <audio controls="controls">
        <source src='/assets/tune.mp3' />
      </audio></p>
  </div>
  <div class="specials">
    <h2 id="yellow">Image of the Week</h2>
    <p><%= image_tag 'joke.png', :class => "fl"  %>
      <span class="title">Florence</span>
      Bikers on Rooftop
      <br /><br /> <%=  link_to image_tag("link.gif"), "http://onebigphoto.com/riders-on-the-roof-of-florence-dome/?utm_source=newsletter&utm_medium=email&utm_campaign=newletter%2Banalytics", :target => "_blank" %></p>
  </div>
  <div class="specials">
    <h2 id="Red">Today's Headlines</h2>
    <p><span id="line">Today a woman shot another who was woman</span></p>
  </div>
  <div id="youtube">
    <h2><%= image_tag 'tube.png' %></h2>
    <iframe width="490" height="250"
            src="//www.youtube.com/embed/H2DPeO9aKV4" allowfullscreen>
    </iframe>
  </div>



</div>
      <div id="articles">

       <%= render 'topics/articles' %>
           </div>
<div class="flcl"></div>
<div id="tagbar2"><span class="KG">Article Search:</span><%= form_tag topics_path, :method => 'get', :remote => true do %>
      <%= text_field_tag :search_query, params[:search_query] %>
      <%= image_submit_tag("login.png")%>
  <% end %></div>
<div id="likes">

  <h1>Likes</h1>
  <hr />
  <%= render 'likes/likes' %>

  <span class="title"><%= link_to 'View All Likes', likes_path %></span>

</div>
<div id="backlog_box">

  <h1>Backlog</h1>

  <hr />

  <div id="backlog">
  <%= render 'topics/list' %>

  </div>



  </div>


<script>
    $(document).ready(function() {
        $('#articles .pagination a').attr('data-remote', 'true');
        $('#backlog .pagination a').attr('data-remote', 'true');
    });</script>

app/views/topics/index.js.erb
$('#articles').html('<%=escape_javascript render "topics/articles" %>');
$('#articles .pagination a').attr('data-remote', 'true');


$('#backlog').html("<%= escape_javascript(render 'topics/list') %>");

//var show_football = (function()
//{
//$("#articles").html( "<%= escape_javascript( render 'topics/football') %>" );
//});

app/views/topics/new.html.erb
<h1>Article Drop</h1>

<%= render 'form' %>

app/views/topics/show.html.erb
<h1><%=  @topic.title %></h1>
<div id="article_show">
  <% if @topic.attachment.file? %>
      <%= image_tag @topic.attachment.url, :class => "picture" %>
  <% end %>
  <%= simple_format(@topic.body) %><br />
    <span id="byline">By:<br />
  <%= @topic.name %>
</span>
</div>


<div id="post_it">
  <% if current_user %>
      <%= render 'posts/form' %>
      <h3>Comments</h3>
      <div id="comments"><%= render 'posts/post' %> </div>
  <% else %>
      <h3>Register To Comment</h3>

      <div id="comments"><span class="green">You Must Register to comment.<br /> It's free and easy so you should really do it!</span></div>

  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for :user do |f| %>
    <div class="acc_font">

      <%= f.text_field :name, :value => "Register Name", :size => "20" %> - <%= f.password_field :password, :value => "Password", :size => "20" %>



    <%= image_submit_tag ("login.png")%>


        </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= user.admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Admin:</b>
  <%= @user.admin %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>